cluster:
  directory: /home/rebeccac/scratch/pipeline/info
  name: simulate_obs
  nodes: 16
  time: 45
  ompnum: 3
  pernode: 16
  mem: 192000M
  system: cedar
  queue_sys: slurm
  account: def-mdobbs
pipeline:
  logging:
    root: DEBUG
    peewee: INFO
    matplotlib: INFO
    h5py: INFO
  save_versions:
  - caput
  - cora
  - draco
  - drift
  - numpy
  - scipy
  - h5py
  - mpi4py
  tasks:
  - type: draco.core.task.SetMPILogging
    params:
      level_rank0: DEBUG
      level_all: WARN
  - type: draco.core.io.LoadProductManager
    out: manager
    params:
      product_directory: /home/rebeccac/scratch/pipeline
  - type: draco.core.io.LoadMaps
    out: map
    params:
      maps:
      - tag: HIgalaxies
        files:
        - /home/rebeccac/scratch/pipeline/Up_Gal.h5
        - /home/rebeccac/scratch/pipeline/Up_Sky.h5
  - type: draco.synthesis.stream.SimulateSidereal
    requires: manager
    in: map
    out: sstack
    params:
      save: true
      output_name: /home/rebeccac/scratch/pipeline/sstream.h5
  - type: draco.synthesis.noise.GaussianNoise
    requires: manager
    in: sstack
    out: sstream_wnoise
    params:
      ndays: 13
      set_weights: true
      add_noise: true
      save: true
      output_name: /home/rebeccac/scratch/pipeline/sstream_gaussian_noise.h5
  - type: draco.analysis.transform.MModeTransform
    requires: manager
    in: sstream_wnoise
    out: mmodes
  - type: draco.analysis.mapmaker.DirtyMapMaker
    requires: manager
    in: mmodes
    out: map_dirty
    params:
      nside: 512
      save: true
      output_name: /home/rebeccac/scratch/response2/outputs/dirty_map1127424.h5
